[dependencies]

[package]
name = "Fundamentos"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ex01"
path = "ex01.rs"

[[bin]]
name = "ex02"
path = "ex02.rs"

[[bin]]
name = "ex03"
path = "ex03.rs"

[[bin]]
name = "ex04"
path = "ex04.rs"

[[bin]]
name = "ex05"
path = "ex05.rs"

